swagger: "2.0"
info:
  description: "Este é um simples webservice para analise de crédito."
  version: "1.0.0"
  title: "Análise de Crédito"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "cidades"
  description: "Crud Cidades"
- name: "clientes"
  description: "Crud Clientes"
- name: "creditos"
  description: "Crud Creditos"
- name: "enderecos"
  description: "Crud Enderecos"
- name: "dependentes"
  description: "Crud Dependentes"
schemes:
- "http"
paths:
  /cidades:
    post:
      tags:
      - "cidades"
      summary: "Adiciona nova cidade"
      description: ""
      operationId: "createCidade"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object Cidade para salvar"
        required: true
        schema:
          $ref: "#/definitions/Cidade"
      responses:
        201:
          description: "Success"
    get:
      tags:
      - "cidades"
      summary: "Lista todas as cidades"
      description: ""
      operationId: "findAllCidade"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cidade object"
        required: false
        schema:
          $ref: "#/definitions/Cidade"
      responses:
        200:
          description: "Success"
  /cidades/{cidade_id}:
    put:
      tags:
      - "cidades"
      summary: "Update uma cidade existente"
      description: ""
      operationId: "updateCidade"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cidade_id"
        in: "path"
        description: "ID Cidade"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
    delete:
      tags:
      - "cidades"
      summary: "Deleta uma cidade existente"
      description: ""
      operationId: "deleteCidade"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cidade_id"
        in: "path"
        description: "ID Cidade"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
  /clientes:
    post:
      tags:
      - "clientes"
      summary: "Adiciona novo cliente"
      description: ""
      operationId: "createCliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object cliente para salvar"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        201:
          description: "Success"
    get:
      tags:
      - "clientes"
      summary: "Lista todas os clientes"
      description: ""
      operationId: "findAllCliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cidade object"
        required: false
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "Success"
  /clientes/{cliente_id}:
    put:
      tags:
      - "clientes"
      summary: "Update um cliente existente"
      description: ""
      operationId: "updateCliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cliente_id"
        in: "path"
        description: "ID Cliente"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
    delete:
      tags:
      - "clientes"
      summary: "Deleta um cliente existente"
      description: ""
      operationId: "deleteCliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cliente_id"
        in: "path"
        description: "ID Cliente"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
  /enderecos:
    post:
      tags:
      - "enderecos"
      summary: "Adiciona novo endereco"
      description: ""
      operationId: "createEndereco"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object cliente para salvar"
        required: true
        schema:
          $ref: "#/definitions/Endereco"
      responses:
        201:
          description: "Success"
    get:
      tags:
      - "enderecos"
      summary: "Lista todas os enderecos"
      description: ""
      operationId: "findAllEndereco"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Endereco object"
        required: false
        schema:
          $ref: "#/definitions/Endereco"
      responses:
        200:
          description: "Success"
  /enderecos/{endereco_id}:
    put:
      tags:
      - "enderecos"
      summary: "Update um endereco existente"
      description: ""
      operationId: "updateEndereco"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "endereco_id"
        in: "path"
        description: "ID endereco"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
    delete:
      tags:
      - "enderecos"
      summary: "Deleta um endereco existente"
      description: ""
      operationId: "deleteEndereco"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "endereco_id"
        in: "path"
        description: "ID endereco"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
  /dependentes:
    post:
      tags:
      - "dependentes"
      summary: "Adiciona novo dependente"
      description: ""
      operationId: "createDependente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object dependente para salvar"
        required: true
        schema:
          $ref: "#/definitions/Dependente"
      responses:
        201:
          description: "Success"
    get:
      tags:
      - "dependentes"
      summary: "Lista todas os dependentes"
      description: ""
      operationId: "findAllDependente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dependente object"
        required: false
        schema:
          $ref: "#/definitions/Dependente"
      responses:
        200:
          description: "Success"
  /dependentes/{dependente_id}:
    put:
      tags:
      - "dependentes"
      summary: "Update um dependente existente"
      description: ""
      operationId: "updateDependente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "dependente_id"
        in: "path"
        description: "ID dependente"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
    delete:
      tags:
      - "dependentes"
      summary: "Deleta um dependente existente"
      description: ""
      operationId: "deleteDependente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "dependente_id"
        in: "path"
        description: "ID dependente"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
  /creditos:
    post:
      tags:
      - "creditos"
      summary: "Adiciona novo credito"
      description: ""
      operationId: "createCredito"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object credito para salvar"
        required: true
        schema:
          $ref: "#/definitions/Credito"
      responses:
        201:
          description: "Success"
    get:
      tags:
      - "creditos"
      summary: "Lista todas os creditos"
      description: ""
      operationId: "findAllCredito"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Credito object"
        required: false
        schema:
          $ref: "#/definitions/Credito"
      responses:
        200:
          description: "Success"
  /creditos/{credito_id}:
    put:
      tags:
      - "creditos"
      summary: "Update um credito existente"
      description: ""
      operationId: "updateCredito"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "credito_id"
        in: "path"
        description: "ID credito"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
    delete:
      tags:
      - "creditos"
      summary: "Deleta um credito existente"
      description: ""
      operationId: "deleteCredito"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "credito_id"
        in: "path"
        description: "ID credito"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success"
definitions:
  Credito:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      cliente:
        $ref: "#/definitions/Cliente"
      aprovado:
        type: "string"
        example: "APROVADO"
        enum:
        - "APROVADO"
        - "DESAPROVADO"
      motivo:
        type: "string"
        example: "RENDABAIXA"
        enum:
        - "APROVADO"
        - "RENDABAIXA"
        - "POLITICACREDITO"
      limite:
        type: "number"
        example: "500"
      dateCreate:
        type: "object"
        example: "2018-11-04 11:11:11"
  Endereco:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      cep:
        type: "string"
        example: "12345678"
      rua:
        type: "string"
        example: "Av. teste"
      cidade:
        $ref: "#/definitions/Cidade"
      estado:
        type: "string"
        example: "AC"
        enum:
        - "AC"
        - "AL"
        - "AP"
        - "AM"
        - "BA"
        - "CE"
        - "DF"
        - "ES"
        - "GO"
        - "MA"
        - "MT"
        - "MS"
        - "MG"
        - "PA"
        - "PB"
        - "PR"
        - "PE"
        - "PI"
        - "RJ"
        - "RN"
        - "RS"
        - "RO"
        - "RR"
        - "SC"
        - "SP"
        - "SE"
        - "TO"
      pais:
        type: "string"
        example: "BR"
        enum:
        - "BR"
      cliente:
        $ref: "#/definitions/Cliente"
  Dependente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
        example: "João"
      cpf:
        type: "string"
        example: "012354789652"
      idade:
        type: "string"
        example: "12"
      sexo:
        type: "string"
        example: "MASCULINO"
        enum:
        - "MASCULINO"
        - "FEMININO"
      estadoCivil:
        type: "string"
        example: "SOLTEIRO"
        enum:
        - "SOLTEIRO"
        - "CASADO"
        - "DIVORCIADO"
        - "VIUVO"
      status:
        type: "string"
        example: "ATIVO"
        enum:
        - "ATIVO"
        - "INATIVO"
      dateCreate:
        type: "object"
        example: "2018-11-04 11:11:11"
  Cliente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
        example: "João"
      cpf:
        type: "string"
        example: "07548558759"
      idade:
        type: "number"
        example: "12"
      sexo:
        type: "string"
        example: "MASCULINO"
        enum:
        - "MASCULINO"
        - "FEMININO"
      estadoCivil:
        type: "string"
        example: "SOLTEIRO"
        enum:
        - "SOLTEIRO"
        - "CASADO"
        - "DIVORCIADO"
        - "VIUVO"
      status:
        type: "string"
        example: "ATIVO"
        enum:
        - "ATIVO"
        - "INATIVO"
      dateCreate:
        type: "object"
        example: "2018-11-04 11:11:11"
      endereco:
        type: "array"
        items:
          $ref: "#/definitions/Endereco"
      dependentes:
        type: "array"
        items:
          $ref: "#/definitions/Dependente"
      creditos:
        type: "array"
        items:
          $ref: "#/definitions/Credito"
  Cidade:
    type: "object"
    required:
    - "nome"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
        example: "Palhoça"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"